name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'

      - name: Use gcloud CLI
        run: gcloud info

      - name: Authorize Docker push
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Build and Push Container
        working-directory: ./backend
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t asia-northeast3-docker.pkg.dev/$PROJECT_ID/fastapi-backend-repo/fastapi-backend:$IMAGE_TAG .
          docker push asia-northeast3-docker.pkg.dev/$PROJECT_ID/fastapi-backend-repo/fastapi-backend:$IMAGE_TAG

      - name: Deploy to Cloud Run
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          gcloud run deploy fastapi-backend \
            --image asia-northeast3-docker.pkg.dev/$PROJECT_ID/fastapi-backend-repo/fastapi-backend:$IMAGE_TAG \
            --platform managed \
            --region asia-northeast3 \
            --allow-unauthenticated \
            --project $PROJECT_ID
